language: python

os:
  - linux

python:
  - 3.8

cache: pip

sudo: required

script:
  - pytest


notifications:
  slack:
    rooms:
      - dropnup:x1ZOJDTXefsq1eLGChjXgKhk#general
      - dropnup:x1ZOJDTXefsq1eLGChjXgKhk#dev

before_script:
  - python3 -m pip install -r requirements.txt